spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 20
      keepAliveSeconds: 120
      queueCapacity: 50
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
    database: 10
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://119.23.242.234:9306/wxdc?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&amp;autoReconnectForPools=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  mapperLocations: classpath:mybatis/sql/*.xml,classpath:mybatis/sql/extend/*.xml

logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

server:
  port: 81

#ticserver:
#  url: http://127.0.0.1:9095/api/push/carcmd
biz:
  scTime: 30000

apiurl: http://119.23.242.234:9095/api
biz_url: http://119.23.242.234:8080
distance: 100
staticPath:  D:\static\common\
znzpurl: http://127.0.0.1:9888/api
obdCheckUrl: http://119.23.242.234:9082/api/3007
